In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import jax
import jax.numpy as jnp

In [3]:
import cr

In [4]:
M = 10
p = 3
N = 5

In [5]:
A = jnp.zeros([M, p])
A

DeviceArray([[0., 0., 0.],
             [0., 0., 0.],
             [0., 0., 0.],
             [0., 0., 0.],
             [0., 0., 0.],
             [0., 0., 0.],
             [0., 0., 0.],
             [0., 0., 0.],
             [0., 0., 0.],
             [0., 0., 0.]], dtype=float32)

In [6]:
B = jnp.ones([N, p])
B

DeviceArray([[1., 1., 1.],
             [1., 1., 1.],
             [1., 1., 1.],
             [1., 1., 1.],
             [1., 1., 1.]], dtype=float32)

In [7]:
import cr.sparse as crs

In [8]:
crs.pairwise_sqr_l2_distances_rw(A, B)

DeviceArray([[3., 3., 3., 3., 3.],
             [3., 3., 3., 3., 3.],
             [3., 3., 3., 3., 3.],
             [3., 3., 3., 3., 3.],
             [3., 3., 3., 3., 3.],
             [3., 3., 3., 3., 3.],
             [3., 3., 3., 3., 3.],
             [3., 3., 3., 3., 3.],
             [3., 3., 3., 3., 3.],
             [3., 3., 3., 3., 3.]], dtype=float32)

In [9]:
A = 3*jnp.ones([M, p])

In [10]:
B = 5*jnp.ones([N, p])

In [11]:
crs.pairwise_sqr_l2_distances_rw(A, B)

DeviceArray([[12., 12., 12., 12., 12.],
             [12., 12., 12., 12., 12.],
             [12., 12., 12., 12., 12.],
             [12., 12., 12., 12., 12.],
             [12., 12., 12., 12., 12.],
             [12., 12., 12., 12., 12.],
             [12., 12., 12., 12., 12.],
             [12., 12., 12., 12., 12.],
             [12., 12., 12., 12., 12.],
             [12., 12., 12., 12., 12.]], dtype=float32)

In [12]:
A = jnp.arange(1, M+1) * jnp.ones((p, 1))
A

DeviceArray([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
             [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
             [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]],            dtype=float32)

In [13]:
B = jnp.arange(2, N+2) * jnp.ones((p, 1))
B

DeviceArray([[2., 3., 4., 5., 6.],
             [2., 3., 4., 5., 6.],
             [2., 3., 4., 5., 6.]], dtype=float32)

In [14]:
crs.pairwise_sqr_l2_distances_rw(A.T, B.T)

DeviceArray([[  3.,  12.,  27.,  48.,  75.],
             [  0.,   3.,  12.,  27.,  48.],
             [  3.,   0.,   3.,  12.,  27.],
             [ 12.,   3.,   0.,   3.,  12.],
             [ 27.,  12.,   3.,   0.,   3.],
             [ 48.,  27.,  12.,   3.,   0.],
             [ 75.,  48.,  27.,  12.,   3.],
             [108.,  75.,  48.,  27.,  12.],
             [147., 108.,  75.,  48.,  27.],
             [192., 147., 108.,  75.,  48.]], dtype=float32)

In [15]:
crs.pairwise_sqr_l2_distances_cw(A, B)

DeviceArray([[  3.,  12.,  27.,  48.,  75.],
             [  0.,   3.,  12.,  27.,  48.],
             [  3.,   0.,   3.,  12.,  27.],
             [ 12.,   3.,   0.,   3.,  12.],
             [ 27.,  12.,   3.,   0.,   3.],
             [ 48.,  27.,  12.,   3.,   0.],
             [ 75.,  48.,  27.,  12.,   3.],
             [108.,  75.,  48.,  27.,  12.],
             [147., 108.,  75.,  48.,  27.],
             [192., 147., 108.,  75.,  48.]], dtype=float32)

In [16]:
cr.sparse.pairwise_sqr_l2_distances_cw(A, B)

DeviceArray([[  3.,  12.,  27.,  48.,  75.],
             [  0.,   3.,  12.,  27.,  48.],
             [  3.,   0.,   3.,  12.,  27.],
             [ 12.,   3.,   0.,   3.,  12.],
             [ 27.,  12.,   3.,   0.,   3.],
             [ 48.,  27.,  12.,   3.,   0.],
             [ 75.,  48.,  27.,  12.,   3.],
             [108.,  75.,  48.,  27.,  12.],
             [147., 108.,  75.,  48.,  27.],
             [192., 147., 108.,  75.,  48.]], dtype=float32)

In [17]:
A

DeviceArray([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
             [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
             [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]],            dtype=float32)

In [18]:
B

DeviceArray([[2., 3., 4., 5., 6.],
             [2., 3., 4., 5., 6.],
             [2., 3., 4., 5., 6.]], dtype=float32)

In [19]:
C = A.T

In [20]:
C

DeviceArray([[ 1.,  1.,  1.],
             [ 2.,  2.,  2.],
             [ 3.,  3.,  3.],
             [ 4.,  4.,  4.],
             [ 5.,  5.,  5.],
             [ 6.,  6.,  6.],
             [ 7.,  7.,  7.],
             [ 8.,  8.,  8.],
             [ 9.,  9.,  9.],
             [10., 10., 10.]], dtype=float32)

In [21]:
D = B.T

In [22]:
D

DeviceArray([[2., 2., 2.],
             [3., 3., 3.],
             [4., 4., 4.],
             [5., 5., 5.],
             [6., 6., 6.]], dtype=float32)

In [23]:
crs.pairwise_l1_distances_rw(C, D)

DeviceArray([[ 3.,  6.,  9., 12., 15.],
             [ 0.,  3.,  6.,  9., 12.],
             [ 3.,  0.,  3.,  6.,  9.],
             [ 6.,  3.,  0.,  3.,  6.],
             [ 9.,  6.,  3.,  0.,  3.],
             [12.,  9.,  6.,  3.,  0.],
             [15., 12.,  9.,  6.,  3.],
             [18., 15., 12.,  9.,  6.],
             [21., 18., 15., 12.,  9.],
             [24., 21., 18., 15., 12.]], dtype=float32)

In [24]:
crs.pairwise_l1_distances_cw(A, B)

DeviceArray([[ 3.,  6.,  9., 12., 15.],
             [ 0.,  3.,  6.,  9., 12.],
             [ 3.,  0.,  3.,  6.,  9.],
             [ 6.,  3.,  0.,  3.,  6.],
             [ 9.,  6.,  3.,  0.,  3.],
             [12.,  9.,  6.,  3.,  0.],
             [15., 12.,  9.,  6.,  3.],
             [18., 15., 12.,  9.,  6.],
             [21., 18., 15., 12.,  9.],
             [24., 21., 18., 15., 12.]], dtype=float32)

In [33]:
crs.pdist_l1_rw(C)

DeviceArray([[ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
             [ 3.,  0.,  3.,  6.,  9., 12., 15., 18., 21., 24.],
             [ 6.,  3.,  0.,  3.,  6.,  9., 12., 15., 18., 21.],
             [ 9.,  6.,  3.,  0.,  3.,  6.,  9., 12., 15., 18.],
             [12.,  9.,  6.,  3.,  0.,  3.,  6.,  9., 12., 15.],
             [15., 12.,  9.,  6.,  3.,  0.,  3.,  6.,  9., 12.],
             [18., 15., 12.,  9.,  6.,  3.,  0.,  3.,  6.,  9.],
             [21., 18., 15., 12.,  9.,  6.,  3.,  0.,  3.,  6.],
             [24., 21., 18., 15., 12.,  9.,  6.,  3.,  0.,  3.],
             [27., 24., 21., 18., 15., 12.,  9.,  6.,  3.,  0.]],            dtype=float32)

In [34]:
crs.pdist_l1_cw(A)

DeviceArray([[ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
             [ 3.,  0.,  3.,  6.,  9., 12., 15., 18., 21., 24.],
             [ 6.,  3.,  0.,  3.,  6.,  9., 12., 15., 18., 21.],
             [ 9.,  6.,  3.,  0.,  3.,  6.,  9., 12., 15., 18.],
             [12.,  9.,  6.,  3.,  0.,  3.,  6.,  9., 12., 15.],
             [15., 12.,  9.,  6.,  3.,  0.,  3.,  6.,  9., 12.],
             [18., 15., 12.,  9.,  6.,  3.,  0.,  3.,  6.,  9.],
             [21., 18., 15., 12.,  9.,  6.,  3.,  0.,  3.,  6.],
             [24., 21., 18., 15., 12.,  9.,  6.,  3.,  0.,  3.],
             [27., 24., 21., 18., 15., 12.,  9.,  6.,  3.,  0.]],            dtype=float32)

In [35]:
A

DeviceArray([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
             [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
             [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]],            dtype=float32)

In [36]:
crs.pairwise_linf_distances_rw(C, D)

DeviceArray([[1., 2., 3., 4., 5.],
             [0., 1., 2., 3., 4.],
             [1., 0., 1., 2., 3.],
             [2., 1., 0., 1., 2.],
             [3., 2., 1., 0., 1.],
             [4., 3., 2., 1., 0.],
             [5., 4., 3., 2., 1.],
             [6., 5., 4., 3., 2.],
             [7., 6., 5., 4., 3.],
             [8., 7., 6., 5., 4.]], dtype=float32)

In [39]:
crs.pairwise_linf_distances_cw(A, B)

DeviceArray([[1., 2., 3., 4., 5.],
             [0., 1., 2., 3., 4.],
             [1., 0., 1., 2., 3.],
             [2., 1., 0., 1., 2.],
             [3., 2., 1., 0., 1.],
             [4., 3., 2., 1., 0.],
             [5., 4., 3., 2., 1.],
             [6., 5., 4., 3., 2.],
             [7., 6., 5., 4., 3.],
             [8., 7., 6., 5., 4.]], dtype=float32)

In [40]:
crs.pdist_linf_rw(C)

DeviceArray([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
             [1., 0., 1., 2., 3., 4., 5., 6., 7., 8.],
             [2., 1., 0., 1., 2., 3., 4., 5., 6., 7.],
             [3., 2., 1., 0., 1., 2., 3., 4., 5., 6.],
             [4., 3., 2., 1., 0., 1., 2., 3., 4., 5.],
             [5., 4., 3., 2., 1., 0., 1., 2., 3., 4.],
             [6., 5., 4., 3., 2., 1., 0., 1., 2., 3.],
             [7., 6., 5., 4., 3., 2., 1., 0., 1., 2.],
             [8., 7., 6., 5., 4., 3., 2., 1., 0., 1.],
             [9., 8., 7., 6., 5., 4., 3., 2., 1., 0.]], dtype=float32)

In [41]:
crs.pdist_linf_cw(B)

DeviceArray([[0., 1., 2., 3., 4.],
             [1., 0., 1., 2., 3.],
             [2., 1., 0., 1., 2.],
             [3., 2., 1., 0., 1.],
             [4., 3., 2., 1., 0.]], dtype=float32)

In [44]:
jnp.mod(jnp.array([1, 2, 2.1, 2.3, 1.0, 3.0]), 1) == 0

DeviceArray([ True,  True, False, False,  True,  True], dtype=bool)

In [57]:
x = jnp.array([1, -2, -2.1, 2.3, 1.0, 3.0, 2.0, -1])

In [51]:
jnp.logical_and(x > 0, jnp.mod(x, 1) == 0)

DeviceArray([ True, False, False, False,  True,  True], dtype=bool)

In [53]:
jnp.mod(x, 2) == 1

DeviceArray([ True, False, False, False,  True,  True], dtype=bool)

In [54]:
jnp.mod(x, 2) == 0

DeviceArray([False,  True, False, False, False, False], dtype=bool)

In [58]:
jnp.logical_and(x > 0, jnp.mod(x, 2) == 1)

DeviceArray([ True, False, False, False,  True,  True, False, False], dtype=bool)

In [59]:
x = 2

In [60]:
jnp.logical_and(x > 0, jnp.mod(x, 2) == 1)

DeviceArray(False, dtype=bool)

In [62]:
jnp.logical_not(jnp.bitwise_and(x, x - 1))

DeviceArray(True, dtype=bool)

In [65]:
x = jnp.arange(1, 17)

In [66]:
jnp.logical_not(jnp.bitwise_and(x, x - 1))

DeviceArray([ True,  True, False,  True, False, False, False,  True,
             False, False, False, False, False, False, False,  True],            dtype=bool)

In [67]:
jnp.floor(x)

DeviceArray([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
             13., 14., 15., 16.], dtype=float32)

In [69]:
jnp.mod

<function jax._src.numpy.lax_numpy.remainder(x1, x2)>

In [70]:
crs.is_integer(x)

DeviceArray([ True,  True,  True,  True,  True,  True,  True,  True,
              True,  True,  True,  True,  True,  True,  True,  True],            dtype=bool)

In [78]:
crs.integer_factors_close_to_sqr_root(16)

(DeviceArray(4, dtype=int32), DeviceArray(4, dtype=int32))

DeviceArray([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
             16], dtype=int32)

In [79]:
sqrt(2)

[autoreload of cr.sparse._src.discrete.number failed: Traceback (most recent call last):
  File "/opt/anaconda3/envs/jax/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/opt/anaconda3/envs/jax/lib/python3.9/site-packages/IPython/extensions/autoreload.py", line 394, in superreload
    module = reload(module)
  File "/opt/anaconda3/envs/jax/lib/python3.9/imp.py", line 314, in reload
    return importlib.reload(module)
  File "/opt/anaconda3/envs/jax/lib/python3.9/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/shailesh/work/carnot/lib/cr-sparse/src/cr/sparse/_src/discrete/number.py", line 17, in <module>
    from sympy.ntheory import factorint
Modul

NameError: name 'sqrt' is not defined